name: music
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  android_intent_plus: ^5.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  get_it: ^7.7.0
  just_audio: ^0.9.39
  just_audio_background: ^0.0.1-beta.13
  on_audio_query: ^2.9.0
  package_info_plus: ^8.0.0
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "assets/icons/logo_background.png"
  adaptive_icon_foreground: "assets/icons/logo_foreground.png"